/**
 * The review-ingest wire shapes, as the contract states them
 * (`docs/review/REVIEW-BACKEND-CONTRACT.md` §4).
 *
 * These are the shapes the client site sends and the shapes it reads back.
 * They are hand-written here rather than inferred from the validators so the
 * schema files can name them without importing zod, and so the contract has
 * one TypeScript statement on this side to be diffed against the client
 * site's. `lib/validators/review.ts` asserts that its schemas produce exactly
 * these types.
 */

/** Where on the page a comment was pinned. Stored as JSONB, verbatim. */
export type ReviewCommentTarget = {
  /** A CSS selector the client site can resolve again; ≤ 1024 chars. */
  selector: string;
  /** 0..1, horizontal position inside the target's box. */
  x: number;
  /** 0..1, vertical position inside the target's box. */
  y: number;
  /** Human-readable name of the element, e.g. "Hero headline"; ≤ 200 chars. */
  label?: string;
};

export type ReviewComment = {
  /** uuid, generated by the client site so retries are idempotent. */
  id: string;
  /** The page it was left on, e.g. "/review/mocks/kit-a"; ≤ 512, starts "/". */
  path: string;
  /** 1..4000 chars, trimmed. */
  body: string;
  target: ReviewCommentTarget;
  /** Integers; the reviewer's viewport when they clicked. */
  viewport: { width: number; height: number };
  /** ISO 8601, set by the client site. */
  createdAt: string;
};

export type ReviewSubmission = {
  /** uuid, generated by the client site. */
  id: string;
  /** Kit id from the client site's registry, e.g. "kit-a". */
  preferredKit: string | null;
  /** Layout id. */
  preferredLayout: string | null;
  /** Mock id. */
  preferredMock: string | null;
  /** "What made you flinch", ≤ 5000. */
  flinch: string | null;
  /** "Anything you'd fight for", ≤ 5000. */
  fightFor: string | null;
  /** Anything else, ≤ 5000. */
  notes: string | null;
  /** Integer; how many live comments the client site counted at submit time. */
  commentCount: number;
  /** ISO 8601. */
  submittedAt: string;
  /**
   * The structured answers (REV-2, M-REV-5). Absent or null on a
   * submission from a form that predates them; every earlier body still
   * validates.
   */
  answers?: ReviewAnswers | null;
};

/** An option as the client site labelled it when the answer was given. */
export type ReviewAnswerOption = {
  /** Stable id from the client site's registry; ≤ 100. */
  id: string;
  /** ≤ 200. */
  label: string;
};

/** Fields every answer carries, whatever its kind. */
type ReviewAnswerBase = {
  /** Stable question id, unique within `items`; ≤ 64, `[a-z0-9.-]`. */
  id: string;
  /** The heading the question sat under on the form; ≤ 100. */
  section: string;
  /** The question as the reviewer read it; ≤ 300. */
  label: string;
};

/**
 * One answered question, self-describing so the stored row and the email
 * read without the client site's code. Unanswered questions are omitted.
 */
export type ReviewAnswer =
  | (ReviewAnswerBase & {
      kind: "rank";
      /** Ranked first to last; 1..20 distinct options. */
      value: ReviewAnswerOption[];
    })
  | (ReviewAnswerBase & {
      kind: "scale";
      /** 0.0..7.0, one decimal — the intake's scale. */
      value: number;
      /** The labels at 0 and at 7; each ≤ 100. */
      ends: { low: string; high: string };
      /** The same slider's intake answer, when there was one. */
      baseline: number | null;
    })
  | (ReviewAnswerBase & {
      kind: "choice";
      value: ReviewAnswerOption;
    })
  | (ReviewAnswerBase & {
      kind: "text";
      /** 1..5000 chars, trimmed. */
      value: string;
    });

export type ReviewAnswers = {
  /** Names the question set, e.g. "kryshan-2026-09"; ≤ 64. */
  schema: string;
  /** In the order the form asked them; 0..80, ids unique. */
  items: ReviewAnswer[];
};
