/**
 * The film pack's seed gallery — 73 sites, tagged from Taylor's two research
 * libraries (film batch one and batch two, August 2026).
 *
 * **The tags are the research's, not invented.** Every `group`, axis, style,
 * and `build` below traces to a line in
 * `docs/websites/…` batch one or two: the axes come from each entry's own
 * "Axes: dark · alive · medium" line, `build` from its achievability rating,
 * and the group from the archetype clusters both libraries converged on. Where
 * a library said "medium" this says `balanced`, which is the same value in the
 * taxonomy's words.
 *
 * `role` is the occupation line the row renders under the name, kept short
 * enough to sit on one line at 375px.
 *
 * `screenshot` is the filename in Taylor's capture folder. Four sites moved
 * since the research was written and carry their current URL here:
 * matiasboucard.com → boucardmatias.com, and the Format subdomains for Mike
 * Call, Othello Banaci, and Petros are now custom domains.
 */
export type SeedSite = {
  slug: string;
  name: string;
  url: string;
  role: string;
  group: string;
  ground: "dark" | "light" | "warm";
  motion: "still" | "quiet" | "alive";
  density: "sparse" | "balanced" | "dense";
  styles: string[];
  build: "template" | "designer" | "custom";
  screenshot: string;
  alt: string;
};

export const FILM_SEED_SITES: SeedSite[] = [
  {
    slug: "aaron-allsop", name: "Aaron Allsop", url: "https://www.aaronallsop.com",
    role: "Writer, director, editor",
    group: "type-first", ground: "light", motion: "still", density: "sparse",
    styles: ["oversized-type", "serif"], build: "template",
    screenshot: "aaronallsop.com.png",
    alt: "A stripped-back white page with the name set large in black display type and almost nothing else.",
  },
  {
    slug: "alexandros-maragos", name: "Alexandros Maragos", url: "https://alexandrosmaragos.com",
    role: "Filmmaker and photographer",
    group: "dark-cinematic", ground: "dark", motion: "still", density: "sparse",
    styles: ["monochrome", "grid"], build: "template",
    screenshot: "alexandrosmaragos.com.png",
    alt: "A full-screen black-and-white still filling the whole window, with a thin nav across the top.",
  },
  {
    slug: "alex-d-levin", name: "Alex D. Levin", url: "https://www.alexdlevin.com",
    role: "Cinematographer",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "sparse",
    styles: ["full-bleed-video"], build: "template",
    screenshot: "alexdlevin.com.png",
    alt: "A dark homepage with a blurred video playing behind the name and a short menu.",
  },
  {
    slug: "andrea-colosio", name: "Andrea Colosio", url: "https://andreacolosiosound.com/en/",
    role: "Sound designer · film and games",
    group: "type-first", ground: "light", motion: "still", density: "balanced",
    styles: ["single-page"], build: "template",
    screenshot: "andreacolosiosound.com.png",
    alt: "A light single-column page led by written copy, with embedded clips further down.",
  },
  {
    slug: "andrea-geremia", name: "Andrea Geremia", url: "https://www.andreageremia.it",
    role: "VFX compositor · feature film",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "dense",
    styles: ["grid", "credits-heavy", "case-studies"], build: "custom",
    screenshot: "andreageremia.it.png",
    alt: "A dark page packed with thumbnail tiles above tabbed filters and dense credit lists.",
  },
  {
    slug: "andrew-cussens", name: "Andrew Cussens", url: "https://www.andrewcussens.com",
    role: "Director · commercials",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video"], build: "designer",
    screenshot: "andrewcussens.com.png",
    alt: "A full-screen video playing edge to edge behind small, widely spaced type.",
  },
  {
    slug: "ariel-methot", name: "Ariel Méthot", url: "https://www.arielmethot.com",
    role: "Cinematographer · fine-art background",
    group: "dark-cinematic", ground: "dark", motion: "still", density: "balanced",
    styles: ["grid", "lightbox-stills"], build: "template",
    screenshot: "arielmethot.com.png",
    alt: "A dark grid of evenly spaced stills, hung like pictures on a gallery wall.",
  },
  {
    slug: "barnaby-roper", name: "Barnaby Roper", url: "http://www.barnabyroper.com",
    role: "Director and photographer · fashion, music",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["hover-preview"], build: "template",
    screenshot: "barnabyroper.com.png",
    alt: "A dark page with one large spotlit piece and small thumbnails beneath it.",
  },
  {
    slug: "matias-boucard", name: "Matias Boucard", url: "https://boucardmatias.com",
    role: "Cinematographer · commercials, music video",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["grid", "hover-preview", "full-bleed-video"], build: "template",
    screenshot: "boucardmatias.com.png",
    alt: "A dark thumbnail grid filling the page, each tile a frame from a different job.",
  },
  {
    slug: "bryan-cooper", name: "Bryan Cooper", url: "https://bryancooperdp.format.com",
    role: "DP and director · US and Japan",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "sparse",
    styles: ["full-bleed-video"], build: "template",
    screenshot: "bryancooperdp.format.com.png",
    alt: "A full-bleed reel playing behind the name, with nothing else above the fold.",
  },
  {
    slug: "bryan-singer", name: "Bryan Singer", url: "https://www.bryansinger.com",
    role: "Filmmaker",
    group: "type-first", ground: "light", motion: "still", density: "dense",
    styles: ["credits-heavy"], build: "template",
    screenshot: "bryansinger.com.png",
    alt: "A plain page of small text and a basic top menu, with long credit listings.",
  },
  {
    slug: "dan-sully", name: "Dan Sully", url: "https://cargocollective.com/dansully",
    role: "Director and photographer · shorts, commercials",
    group: "type-first", ground: "light", motion: "still", density: "sparse",
    styles: ["index-nav", "monochrome"], build: "template",
    screenshot: "cargocollective.com:dansully.png",
    alt: "A near-empty white page listing categories as plain text links, no images.",
  },
  {
    slug: "catherine-goldschmidt", name: "Catherine Goldschmidt", url: "https://catherinegoldschmidt.com",
    role: "Cinematographer · television, features",
    group: "light-editorial", ground: "light", motion: "still", density: "balanced",
    styles: ["one-colour-accent", "case-studies"], build: "template",
    screenshot: "catherinegoldschmidt.com.png",
    alt: "A white editorial page where titles and links are a single bright purple against black body copy.",
  },
  {
    slug: "chris-roebuck", name: "Chris Roebuck", url: "https://www.chrisroebuck.tv",
    role: "Film editor · commercials, music video",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["splash-gate", "grid"], build: "template",
    screenshot: "chrisroebuck.tv.png",
    alt: "A dark entry screen that has to be clicked through before the work grid appears.",
  },
  {
    slug: "christopher-guest", name: "Christopher Guest", url: "https://www.christopherguest.ca",
    role: "Producer, editor, composer",
    group: "type-first", ground: "light", motion: "still", density: "balanced",
    styles: ["index-nav"], build: "template",
    screenshot: "christopherguest.ca.png",
    alt: "A conventional light page with a plain menu and a short written biography.",
  },
  {
    slug: "christopher-mably", name: "Christopher Mably", url: "https://christophermably.com",
    role: "Cinematographer, CSC",
    group: "dark-cinematic", ground: "dark", motion: "quiet", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "christophermably.com.png",
    alt: "A plain dark grid of video thumbnails with no styling beyond the work itself.",
  },
  {
    slug: "corrado-serri", name: "Corrado Serri", url: "https://corradoserri.com",
    role: "Cinematographer · Rome",
    group: "dark-cinematic", ground: "dark", motion: "still", density: "balanced",
    styles: ["grid", "letterbox"], build: "template",
    screenshot: "corradoserri.com.png",
    alt: "A dark grid of letterboxed frames, each held in a wide cinematic crop.",
  },
  {
    slug: "dale-mccready", name: "Dale Elena McCready", url: "https://www.dalemccready.com",
    role: "Cinematographer · television drama",
    group: "dark-cinematic", ground: "dark", motion: "quiet", density: "balanced",
    styles: ["single-page", "grid"], build: "template",
    screenshot: "dalemccready.com.png",
    alt: "A long page with a fixed top menu jumping between sections over background imagery.",
  },
  {
    slug: "daniel-bencomo", name: "Daniel Bencomo", url: "https://www.danielbencomo.com",
    role: "Wedding filmmaker",
    group: "warm-textured", ground: "warm", motion: "alive", density: "balanced",
    styles: ["grain", "full-bleed-video"], build: "designer",
    screenshot: "danielbencomo.com.png",
    alt: "An off-white page with a fine grain texture over it and a muted film playing behind.",
  },
  {
    slug: "duran-levinson", name: "Duran Levinson", url: "https://www.duranlevinson.com/hello/musicvideo",
    role: "Director · Berlin and South Africa",
    group: "warm-textured", ground: "warm", motion: "alive", density: "dense",
    styles: ["oversized-type", "one-colour-accent"], build: "template",
    screenshot: "duranlevinson.com.png",
    alt: "A bright pink page carrying huge type and many small pieces of work at once.",
  },
  {
    slug: "edna-luise", name: "Edna Luise Biesold", url: "https://www.ednaluise.com/audition",
    role: "Filmmaker · inclusive narrative",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "sparse",
    styles: ["hover-preview", "grain"], build: "template",
    screenshot: "ednaluise.com.png",
    alt: "A dark page with animated black-and-white polaroid frames as the way in.",
  },
  {
    slug: "edoardo-smerilli", name: "Edoardo Smerilli", url: "https://edoardosmerilli.com",
    role: "Film director · cinema, comics, CGI",
    group: "statement", ground: "dark", motion: "alive", density: "balanced",
    styles: ["horizontal-scroll", "oversized-type"], build: "custom",
    screenshot: "edoardosmerilli.com.png",
    alt: "A dark three-colour page that scrolls sideways, turning like the pages of a comic.",
  },
  {
    slug: "emily-barresi", name: "Emily Barresi", url: "https://www.emilybarresi.com/the-fifth-floor",
    role: "Visual artist and filmmaker",
    group: "light-editorial", ground: "light", motion: "still", density: "sparse",
    styles: ["lightbox-stills"], build: "template",
    screenshot: "emilybarresi.com.png",
    alt: "A white page with generous space and a small gallery of stills before any film.",
  },
  {
    slug: "feels-digital", name: "Feels Digital", url: "https://www.feels.digital",
    role: "Visual content studio · Bahrain",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video"], build: "designer",
    screenshot: "feels.digital.png",
    alt: "A sleek dark studio page with motion graphics running behind the titles.",
  },
  {
    slug: "filipe-correia-santos", name: "Filipe Correia Santos", url: "https://www.filipecorreiasantos.com",
    role: "Film director",
    group: "light-editorial", ground: "light", motion: "still", density: "dense",
    styles: ["letterbox"], build: "designer",
    screenshot: "filipecorreiasantos.com.png",
    alt: "Stacked letterboxed frames running down a light page like a strip of film, with vertical text beside them.",
  },
  {
    slug: "fiona-ziegler", name: "Fiona Ziegler", url: "https://fionaziegler.com",
    role: "Filmmaker and director",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "sparse",
    styles: ["full-bleed-video"], build: "template",
    screenshot: "fionaziegler.com.png",
    alt: "A full-screen film playing behind a small elegant menu, nothing else in view.",
  },
  {
    slug: "jacob-mckee", name: "Jacob McKee", url: "https://jacobmckee.com",
    role: "Colorist · features, commercials, music video",
    group: "type-first", ground: "light", motion: "alive", density: "sparse",
    styles: ["index-nav", "oversized-type", "hover-preview"], build: "custom",
    screenshot: "jacobmckee.com.png",
    alt: "A white page with no hero image — just three lowercase words as the whole navigation.",
  },
  {
    slug: "jake-weisler", name: "Jake Weisler", url: "https://www.jakeweislerfilms.com",
    role: "Wedding filmmaker · Salt Lake City",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video"], build: "template",
    screenshot: "jakeweislerfilms.com.png",
    alt: "A dark template homepage with a full-screen video hero and a standard menu bar.",
  },
  {
    slug: "jose-betancourt", name: "José Betancourt", url: "https://www.jodejos.com",
    role: "Film director and DP",
    group: "light-editorial", ground: "light", motion: "still", density: "balanced",
    styles: ["horizontal-scroll", "serif", "letterbox"], build: "template",
    screenshot: "jodejos.com.png",
    alt: "A light page scrolling sideways, each work captioned in serif type like an artist's monograph.",
  },
  {
    slug: "joel-knoernschild", name: "Joel Knoernschild", url: "https://joelknoernschild.com",
    role: "Director · documentary",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "joelknoernschild.com.png",
    alt: "Large dark cover blocks stacked down the page, one per film.",
  },
  {
    slug: "joel-santos", name: "Joel Santos", url: "https://www.joelsantos.net",
    role: "Travel photographer and documentary filmmaker",
    group: "light-editorial", ground: "light", motion: "still", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "joelsantos.net.png",
    alt: "High-resolution travel photographs on a clean white layout with heavy black type.",
  },
  {
    slug: "johnny-harris", name: "Johnny Harris", url: "https://www.johnnyharris.ch",
    role: "Journalist and filmmaker",
    group: "warm-textured", ground: "warm", motion: "quiet", density: "balanced",
    styles: ["grain", "serif"], build: "template",
    screenshot: "johnnyharris.ch.png",
    alt: "A beige, paper-textured page laid out like a travel journal, with collaged frames.",
  },
  {
    slug: "john-willner", name: "John Willner", url: "https://www.johnwillner.com",
    role: "Filmmaker and cinematographer",
    group: "dark-cinematic", ground: "dark", motion: "quiet", density: "sparse",
    styles: ["oversized-type"], build: "template",
    screenshot: "johnwillner.com.png",
    alt: "A dark minimal page with the name set large and a very simple structure beneath.",
  },
  {
    slug: "julia-rossetti", name: "Julia Rossetti", url: "https://juliarossetti.com",
    role: "Colorist · Barcelona",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "dense",
    styles: ["grid", "hover-preview"], build: "template",
    screenshot: "juliarossetti.com.png",
    alt: "A wall-to-wall dark grid of graded frames with category filters above it.",
  },
  {
    slug: "kelsey-hannah-walsh", name: "Kelsey Hannah Walsh", url: "https://www.kelseyhannahwalsh.com",
    role: "Production designer · film, fashion, music video",
    group: "stills-credits", ground: "light", motion: "still", density: "balanced",
    styles: ["grid", "lightbox-stills"], build: "template",
    screenshot: "kelseyhannahwalsh.com.png",
    alt: "A clean light grid of production stills, each opening to a single-column project page.",
  },
  {
    slug: "kirill-groshev", name: "Kirill Groshev", url: "https://kirillgroshev.com",
    role: "Cinematographer",
    group: "warm-textured", ground: "dark", motion: "quiet", density: "balanced",
    styles: ["mono", "grain", "one-colour-accent"], build: "designer",
    screenshot: "kirillgroshev.com.png",
    alt: "Orange monospaced type on black, with rounded image corners and a grainy, retro-futuristic feel.",
  },
  {
    slug: "lauren-sick", name: "Lauren Sick", url: "https://laurensick.com",
    role: "Writer and director · narrative, branded",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video", "grid"], build: "template",
    screenshot: "laurensick.com.png",
    alt: "A dark page opening on a video cover, with featured thumbnails below it.",
  },
  {
    slug: "salomon-ligthelm", name: "Salomon Ligthelm", url: "https://www.ligthelm.work",
    role: "Director · New York",
    group: "statement", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video"], build: "custom",
    screenshot: "ligthelm.work.png",
    alt: "An immersive dark page of looping film with navigation that behaves unlike a normal menu.",
  },
  {
    slug: "lluis-murua", name: "Lluís Murúa", url: "http://lluismurua.com",
    role: "Editor · music video",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["grid", "hover-preview"], build: "template",
    screenshot: "lluismurua.com.png",
    alt: "A dark grid of featured thumbnails that play a clip when the pointer rests on them.",
  },
  {
    slug: "lorraine-khamali", name: "Lorraine Khamali", url: "https://lorrainekhamali.format.com/zigzag",
    role: "Director and cinematographer · London",
    group: "warm-textured", ground: "warm", motion: "alive", density: "balanced",
    styles: ["grain", "grid"], build: "template",
    screenshot: "lorrainekhamali.format.com.png",
    alt: "A warm, grainy page with work staggered across the grid in a vintage palette.",
  },
  {
    slug: "mackai-sharp", name: "Mackai Sharp", url: "https://www.mackaisharp.com",
    role: "Cinematographer · stills and video",
    group: "light-editorial", ground: "light", motion: "alive", density: "balanced",
    styles: ["hover-preview", "single-page"], build: "template",
    screenshot: "mackaisharp.com.png",
    alt: "A light page where work is staggered freely down one column rather than aligned to a grid.",
  },
  {
    slug: "maggie-whitaker", name: "Maggie Whitaker", url: "https://maggiewhitaker.com/film/",
    role: "Costume designer · film and television",
    group: "stills-credits", ground: "light", motion: "still", density: "dense",
    styles: ["grid", "index-nav"], build: "template",
    screenshot: "maggiewhitaker.com.png",
    alt: "A dense light grid of costume stills with a text index listing every production.",
  },
  {
    slug: "malte-rosenfeld", name: "Malte Rosenfeld", url: "https://malterosenfeld.com",
    role: "Cinematographer · portraiture, documentary",
    group: "stills-credits", ground: "dark", motion: "still", density: "balanced",
    styles: ["lightbox-stills", "letterbox", "grid"], build: "template",
    screenshot: "malterosenfeld.com.png",
    alt: "A dark grid of frames that open full-size in a lightbox rather than playing as video.",
  },
  {
    slug: "marcella-caudill", name: "Marcella Caudill", url: "https://www.marcellacostumes.com/designportfolio",
    role: "Costume designer · Atlanta",
    group: "stills-credits", ground: "light", motion: "still", density: "balanced",
    styles: ["grid", "lightbox-stills"], build: "template",
    screenshot: "marcellacostumes.com.png",
    alt: "A light gallery grid of production stills from television and film costume work.",
  },
  {
    slug: "matt-davella", name: "Matt D'Avella", url: "https://www.mattdavella.com",
    role: "Filmmaker · documentary, online video",
    group: "light-editorial", ground: "light", motion: "quiet", density: "balanced",
    styles: ["oversized-type"], build: "template",
    screenshot: "mattdavella.com.png",
    alt: "A clean modern page with bold headline type and a faint texture behind it.",
  },
  {
    slug: "matt-jacobson", name: "Matt M Jacobson", url: "https://www.mattjacobsonsound.com/sound-portfolio",
    role: "Sound designer and editor · film",
    group: "type-first", ground: "dark", motion: "alive", density: "balanced",
    styles: ["index-nav"], build: "template",
    screenshot: "mattjacobsonsound.com.png",
    alt: "A dark page listing work as text, with clips embedded beneath each entry to be heard.",
  },
  {
    slug: "maurine-pagani", name: "Maurine Pagani", url: "https://www.maurinepagani.com",
    role: "Filmmaker · fashion and art",
    group: "warm-textured", ground: "light", motion: "alive", density: "sparse",
    styles: ["grain", "single-page"], build: "template",
    screenshot: "maurinepagani.com.png",
    alt: "One project filling the whole screen at a time, in a grainy vintage 8mm palette.",
  },
  {
    slug: "michael-williams", name: "Michael Williams", url: "https://www.michaelwilliamsvideo.com",
    role: "Videographer, editor, director",
    group: "light-editorial", ground: "light", motion: "still", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "michaelwilliamsvideo.com.png",
    alt: "A tidy light portfolio grid with clean type and a conventional layout.",
  },
  {
    slug: "michele-michel", name: "Michele Michel", url: "https://michelemichel.com",
    role: "Costume designer · film, television, fashion",
    group: "stills-credits", ground: "light", motion: "still", density: "balanced",
    styles: ["grid", "index-nav"], build: "template",
    screenshot: "michelemichel.com.png",
    alt: "A light page split by category — film, television, illustrations — each a grid of stills.",
  },
  {
    slug: "mike-call", name: "Mike Call", url: "https://www.mikecallpictures.com",
    role: "Filmmaker and DP · climbing, documentary",
    group: "stills-credits", ground: "dark", motion: "still", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "mikecallpictures.com.png",
    alt: "A muted dark grid of documentary stills from expedition and climbing work.",
  },
  {
    slug: "mona-mekkawi", name: "Mona Mekkawi", url: "https://www.monamekkawi.com",
    role: "Production designer and art director",
    group: "stills-credits", ground: "light", motion: "still", density: "balanced",
    styles: ["grid", "lightbox-stills"], build: "template",
    screenshot: "monamekkawi.com.png",
    alt: "A conventional light grid of art-department stills organised by category.",
  },
  {
    slug: "myrthe-mosterman", name: "Myrthe Mosterman", url: "https://myrthemosterman.com",
    role: "Cinematographer",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "sparse",
    styles: ["full-bleed-video", "single-page"], build: "template",
    screenshot: "myrthemosterman.com.png",
    alt: "A single dark cover image filling the window, with the work stacked in one column below.",
  },
  {
    slug: "nabil", name: "Nabil", url: "https://www.nabil.com",
    role: "Director and photographer · music",
    group: "dark-cinematic", ground: "dark", motion: "quiet", density: "sparse",
    styles: ["grid", "monochrome"], build: "designer",
    screenshot: "nabil.com.png",
    alt: "A stripped-back dark page under a single mononym, with images doing all the talking.",
  },
  {
    slug: "neels-castillon", name: "Neels Castillon", url: "https://www.neelscastillon.com",
    role: "Film director and artist · Paris",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video", "oversized-type"], build: "template",
    screenshot: "neelscastillon.com.png",
    alt: "Full-width video running under large type on a dark, uncluttered page.",
  },
  {
    slug: "nick-emerson", name: "Nick Emerson", url: "http://nickemersonmusic.com/sounddesignportfolio",
    role: "Composer and sound designer · games, film",
    group: "type-first", ground: "dark", motion: "still", density: "dense",
    styles: ["index-nav", "credits-heavy"], build: "template",
    screenshot: "nickemersonmusic.com.png",
    alt: "A dark, text-led page that opens with written background before any embedded media.",
  },
  {
    slug: "nick-sanders", name: "Nick Sanders", url: "https://nicksanders.tv",
    role: "Colorist · Atlanta",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["grid", "hover-preview"], build: "template",
    screenshot: "nicksanders.tv.png",
    alt: "A near-black two-column grid that mimics the viewing conditions of a grading suite.",
  },
  {
    slug: "othello-banaci", name: "Othello Banaci", url: "https://www.othellobanaci.tv",
    role: "Filmmaker and DP · documentary",
    group: "stills-credits", ground: "dark", motion: "still", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "othellobanaci.tv.png",
    alt: "A clean dark grid of documentary frames, the work presented without decoration.",
  },
  {
    slug: "weronika-izdebska", name: "Weronika Maria Izdebska", url: "https://www.ovors.com/films",
    role: "Filmmaker and photographer",
    group: "light-editorial", ground: "light", motion: "still", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "ovors.com.png",
    alt: "A light page where stills and films sit together in a staggered editorial grid.",
  },
  {
    slug: "patrick-fileti", name: "Patrick Fileti", url: "https://www.patrickfileti.com",
    role: "Filmmaker · emotive, non-actor driven",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video"], build: "template",
    screenshot: "patrickfileti.com.png",
    alt: "A dark cover of full-width film with thumbnails stacked underneath.",
  },
  {
    slug: "petros", name: "Petros", url: "https://www.petros.productions",
    role: "Cinematographer · festival shorts",
    group: "light-editorial", ground: "light", motion: "still", density: "balanced",
    styles: ["grid"], build: "template",
    screenshot: "petros.productions.png",
    alt: "A light staggered grid that reads as full even with a modest number of pieces.",
  },
  {
    slug: "philippe-gnannt", name: "Philippe Gnannt", url: "https://www.philippegnannt.com",
    role: "Film editor · documentary, commercials",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "sparse",
    styles: ["index-nav", "hover-preview", "full-bleed-video"], build: "designer",
    screenshot: "philippegnannt.com.png",
    alt: "A dark list of project titles where resting on one swaps the full-screen clip behind it.",
  },
  {
    slug: "rafa-g-arroyo", name: "Rafa G. Arroyo", url: "http://rafagarroyo.com",
    role: "Cinematographer · Madrid",
    group: "stills-credits", ground: "dark", motion: "still", density: "sparse",
    styles: ["lightbox-stills", "grain"], build: "template",
    screenshot: "rafagarroyo.com.png",
    alt: "A single spotlit frame on a dark page, the rest opening as full-size stills.",
  },
  {
    slug: "red-creative-films", name: "Red Creative Films", url: "https://www.redcreativefilms.com",
    role: "One-person video brand",
    group: "dark-cinematic", ground: "dark", motion: "quiet", density: "balanced",
    styles: ["oversized-type", "one-colour-accent"], build: "template",
    screenshot: "redcreativefilms.com.png",
    alt: "Bold white type on black with red accents marking the links and headings.",
  },
  {
    slug: "rm-wedding-films", name: "RM Wedding Films", url: "https://rmweddingfilms.co.uk",
    role: "Wedding videographer · UK",
    group: "warm-textured", ground: "warm", motion: "alive", density: "balanced",
    styles: ["single-page"], build: "template",
    screenshot: "rmweddingfilms.co.uk.png",
    alt: "A warm light page scrolling with parallax through films and client testimonials.",
  },
  {
    slug: "rob-chiu", name: "Rob Chiu", url: "https://www.robchiu.com",
    role: "Director · atmospheric, sound-led",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "balanced",
    styles: ["full-bleed-video"], build: "template",
    screenshot: "robchiu.com.png",
    alt: "Muted dark blocks of featured work cycling as a slideshow across the page.",
  },
  {
    slug: "rodrigo-robinet", name: "Rodrigo Robinet", url: "https://rodrigorobinet.com/portfolio",
    role: "Sound designer",
    group: "type-first", ground: "dark", motion: "alive", density: "sparse",
    styles: ["full-bleed-video"], build: "template",
    screenshot: "rodrigorobinet.com.png",
    alt: "A dark page led by a single sound reel, with a few clips listed beneath it.",
  },
  {
    slug: "ryan-darst", name: "Ryan Darst", url: "https://www.ryandarst.com",
    role: "Writer, director, editor",
    group: "type-first", ground: "light", motion: "still", density: "dense",
    styles: ["index-nav", "grid"], build: "template",
    screenshot: "ryandarst.com.png",
    alt: "A light page with a fixed index of projects down the left, reading like a working résumé.",
  },
  {
    slug: "samuel-warnants", name: "Samuel Warnants", url: "https://samuelwarnants.cargo.site",
    role: "Editor and VFX · Brussels",
    group: "type-first", ground: "light", motion: "quiet", density: "balanced",
    styles: ["index-nav", "mono", "credits-heavy"], build: "template",
    screenshot: "samuelwarnants.cargo.site.png",
    alt: "A single column of text divided by horizontal rules, structured like a filmography document.",
  },
  {
    slug: "steven-olver", name: "Steven Olver", url: "https://www.stevenolver.com",
    role: "Motion designer and VFX · London",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "dense",
    styles: ["full-bleed-video", "grid", "single-page"], build: "template",
    screenshot: "stevenolver.com.png",
    alt: "A long dark single page opening on a showreel, then filters, a timeline and an awards wall.",
  },
  {
    slug: "tao-tajima", name: "Tao Tajima", url: "https://taotajima.jp",
    role: "Director · Tokyo",
    group: "statement", ground: "dark", motion: "alive", density: "sparse",
    styles: ["monochrome", "index-nav", "full-bleed-video"], build: "custom",
    screenshot: "taotajima.jp.png",
    alt: "A stark black-and-white page of numbered works where transitions ripple like a liquid effect.",
  },
  {
    slug: "the-directors-bureau", name: "The Directors Bureau", url: "https://www.thedirectorsbureau.com",
    role: "Production company · director roster",
    group: "dark-cinematic", ground: "dark", motion: "alive", density: "dense",
    styles: ["grid", "index-nav"], build: "custom",
    screenshot: "thedirectorsbureau.com.png",
    alt: "A dark roster page listing many directors, each opening into their own reel.",
  },
  {
    slug: "tim-flower", name: "Tim Flower", url: "https://timflower.co.nz",
    role: "Cinematographer · New Zealand",
    group: "light-editorial", ground: "light", motion: "alive", density: "balanced",
    styles: ["grid", "hover-preview"], build: "template",
    screenshot: "timflower.co.nz.png",
    alt: "A light page whose grid lines draw themselves on load, with clips playing on hover.",
  },
  {
    slug: "zoe-koperski", name: "Zoe Koperski", url: "https://zoe-koperski.com",
    role: "Production designer and art director",
    group: "stills-credits", ground: "light", motion: "still", density: "balanced",
    styles: ["grid", "credits-heavy"], build: "template",
    screenshot: "zoe-koperski.com.png",
    alt: "A light grid of art-department work where every project carries its own client and director tags.",
  },
];
